# Generated by Django 5.2.6 on 2025-09-27 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Confirence',
            fields=[
                ('confirence_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('theme', models.CharField(choices=[('ai', 'computer science & ia'), ('se', 'science & eng'), ('sc', 'education'), ('it', 'interdisciplinary themes')], max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('submission_id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('abstract', models.TextField()),
                ('keywords', models.TextField()),
                ('paper', models.FileField(upload_to='papers/')),
                ('status', models.CharField(choices=[('submitted', 'submitted'), ('under review', 'under review'), ('accepted', 'accepted'), ('rejected', 'rejected')], max_length=50)),
                ('submission_date', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confirence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='ConfirencApp.confirence')),
            ],
        ),
    ]
